serverAddr = "47.92.237.29"
serverPort = 7000
auth.method = "token"
auth.token = "WeVV4bezpLVXsIH4"

[[visitors]]
name = "mzy_shh_bt_visitor2"
type = "stcp"
serverName = "web-mzy"
secretKey = "dm@q1w2~e3r4~mzy"
bindAddr = "127.0.0.1"
bindPort = 6008
